services:
  agent-inventory:
    container_name: agent-inventory
    build:
      context: .
      dockerfile: apps/agents/inventory/Dockerfile
    ports:
      - "161:161/udp"
    restart: unless-stopped

  agent-orders:
    container_name: agent-orders
    build:
      context: .
      dockerfile: apps/agents/orders/Dockerfile
    ports:
      - "1161:161/udp"
    restart: unless-stopped

  agent-payments:
    container_name: agent-payments
    build:
      context: .
      dockerfile: apps/agents/payments/Dockerfile
    ports:
      - "2161:161/udp"
    restart: unless-stopped

  agent-users:
    container_name: agent-users
    build:
      context: .
      dockerfile: apps/agents/users/Dockerfile
    ports:
      - "3161:161/udp"
    restart: unless-stopped

  agent-notifications:
    container_name: agent-notifications
    build:
      context: .
      dockerfile: apps/agents/notifications/Dockerfile
    ports:
      - "4161:161/udp"
    restart: unless-stopped

networks:
  default:
    name: sdn-agents

  portal:
    container_name: portal
    build:
      context: .
      dockerfile: apps/portal/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - agent-inventory
      - agent-orders
      - agent-payments
      - agent-users
      - agent-notifications
    restart: unless-stopped

