apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-client
  namespace: sdn-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-client
  template:
    metadata:
      labels:
        app: web-client
    spec:
      containers:
      - name: web-client
        image: ananyakaligal/sdn-portal:latest
---
apiVersion: v1
kind: Service
metadata:
  name: web-client-service
  namespace: sdn-project
spec:
  selector:
    app: web-client
  ports:
  - port: 3000
    targetPort: 3000
  type: LoadBalancer
