apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-client
  namespace: sdn-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-client
  template:
    metadata:
      labels:
        app: web-client
    spec:
      containers:
      - name: web-client
        image: sdn-portal:latest
        imagePullPolicy: Never
        env:
        - name: NODE_ENV
          value: "production"
        - name: NEXT_PUBLIC_MANAGER_URL
          value: "http://snmp-manager-service:3001"
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
---
apiVersion: v1
kind: Service
metadata:
  name: web-client-service
  namespace: sdn-project
spec:
  selector:
    app: web-client
  ports:
  - port: 3000
    targetPort: 3000
  type: LoadBalancer
