apiVersion: apps/v1
kind: Deployment
metadata:
  name: snmp-manager
  namespace: sdn-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snmp-manager
  template:
    metadata:
      labels:
        app: snmp-manager
    spec:
      containers:
      - name: snmp-manager
        image: sdn-manager:latest
        imagePullPolicy: Never
        env:
        - name: NODE_ENV
          value: "production"
        ports:
        - containerPort: 3001
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: snmp-manager-service
  namespace: sdn-project
spec:
  selector:
    app: snmp-manager
  ports:
  - port: 3001
    targetPort: 3001
  type: ClusterIP
